resilience4j:
  retry:
    instances:
      basic:
         maxRetryAttemps: 3
         waitDuration: 1s

  ratelimiter:
    instances:
      limitbasic:
        limitForPeriod: 2
        limitRefreshPeriod: 5s
        timeoutDuration: 1